language: go

go:
  - "1.11"
  - "stable"

before_install:
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - go test -v -race -covermode=atomic -coverprofile=coverage.out
  - go test ./... -race

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  - GO111MODULE=on