# hugo server --themesDir ... --baseURL=http://0.0.0.0:1313/example

baseURL: https://steinfletcher.github.io
title: apitest
theme: hugo-book

# Book configuration
disablePathToLower: true
enableGitInfo: true

PygmentsCodeFences: true
PygmentsStyle: tango

params:
  # (Optional, default true) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  BookShowToC: true

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookMenuBundle: /menu

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection: docs

  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  BookMenuBundleActiveLinkColor: #004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  BookEnableJS: true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/steinfletcher/apitest

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath: edit/master/docs/content